In [42]:
import pandas as pd
df = pd.read_csv('/content/rugby_stats.csv')
df

,MatchID,Date,HomeTeam,AwayTeam,Venue,Tournament,Round,HomeScore,AwayScore,HomeTriesScored,...,PlayerCaps,PlayerTries,PlayerConversions,PlayerPenalties,PlayerYellowCards,PlayerRedCards,TacklesMade,TacklesMissed,MetresCarried,Result
0,1000,2019-04-08,France XV,New Zealand All Blacks,"Twickenham, London",World Rugby U20 Championship,2,52,5,8,...,104.0,0,0,0,0,0,13.0,5.0,71.0,Home Win
1,1001,2016-07-03,Georgia Rugby,Romania Rugby,"Estadio Jose Amalfitani, Buenos Aires",The Rugby Championship,6,33,11,3,...,86.0,2,0,0,0,0,2.0,2.0,136.0,Home Win
2,1002,2015-06-13,South Africa Springboks,Argentina Pumas,"Aviva Stadium, Dublin",Rugby World Cup,4,44,36,5,...,66.0,3,0,0,0,0,3.0,2.0,160.0,Home Win
3,1003,2023-05-25,New Zealand All Blacks,Ireland Rugby,"ANZ National Stadium, Suva",The Rugby Championship,2,22,51,4,...,NaN,2,0,0,0,0,16.0,0.0,153.0,Away Win
4,1004,2022-02-25,England Rugby,France XV,"Estadio Jose Amalfitani, Buenos Aires",Rugby Europe Championship,3,20,51,2,...,NaN,2,0,0,0,0,3.0,3.0,NaN,Away Win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4065,4005,2016-09-14,Canada Rugby,Samoa Rugby,"Teufaiva Stadium, Tonga",Autumn Internationals,7,34,48,6,...,59.0,3,0,0,0,0,7.0,2.0,176.0,Away Win
4066,3860,2024-02-06,Canada Rugby,Tonga Rugby,"National Stadium, Tokyo",Rugby World Cup,7,30,56,5,...,63.0,0,0,0,1,0,9.0,8.0,43.0,Away Win
4067,3854,2018-03-05,Canada Rugby,USA Eagles,"ANZ National Stadium, Suva",Pacific Nations Cup,4,50,23,7,...,51.0,1,0,0,0,0,12.0,7.0,92.0,Home Win
4068,2571,2021-05-01,Australia Wallabies,Italy Rugby,"Teufaiva Stadium, Tonga",Rugby Europe Championship,4,6,47,0,...,8.0,0,0,0,0,0,NaN,0.0,83.0,Away Win
4069,4806,2021-05-26,Argentina Pumas,Spain Rugby,"Stadium Australia, Sydney",The Rugby Championship,4,43,27,7,...,93.0,2,0,2,0,0,7.0,4.0,46.0,Home Win

In [43]:
df.head()

,MatchID,Date,HomeTeam,AwayTeam,Venue,Tournament,Round,HomeScore,AwayScore,HomeTriesScored,...,PlayerCaps,PlayerTries,PlayerConversions,PlayerPenalties,PlayerYellowCards,PlayerRedCards,TacklesMade,TacklesMissed,MetresCarried,Result
0,1000,2019-04-08,France XV,New Zealand All Blacks,"Twickenham, London",World Rugby U20 Championship,2,52,5,8,...,104.0,0,0,0,0,0,13.0,5.0,71.0,Home Win
1,1001,2016-07-03,Georgia Rugby,Romania Rugby,"Estadio Jose Amalfitani, Buenos Aires",The Rugby Championship,6,33,11,3,...,86.0,2,0,0,0,0,2.0,2.0,136.0,Home Win
2,1002,2015-06-13,South Africa Springboks,Argentina Pumas,"Aviva Stadium, Dublin",Rugby World Cup,4,44,36,5,...,66.0,3,0,0,0,0,3.0,2.0,160.0,Home Win
3,1003,2023-05-25,New Zealand All Blacks,Ireland Rugby,"ANZ National Stadium, Suva",The Rugby Championship,2,22,51,4,...,NaN,2,0,0,0,0,16.0,0.0,153.0,Away Win
4,1004,2022-02-25,England Rugby,France XV,"Estadio Jose Amalfitani, Buenos Aires",Rugby Europe Championship,3,20,51,2,...,NaN,2,0,0,0,0,3.0,3.0,NaN,Away Win

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4070 entries, 0 to 4069
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   MatchID            4070 non-null   int64
 1   Date               4070 non-null   object
 2   HomeTeam           4070 non-null   object
 3   AwayTeam           4070 non-null   object
 4   Venue              3982 non-null   object
 5   Tournament         3979 non-null   object
 6   Round              4070 non-null   int64
 7   HomeScore          4070 non-null   int64
 8   AwayScore          4070 non-null   int64
 9   HomeTriesScored    4070 non-null   int64
 10  AwayTriesScored    4070 non-null   int64
 11  HomePossession%    4070 non-null   int64
 12  AwayPossession%    4070 non-null   int64
 13  HomeYellowCards    4070 non-null   int64
 14  AwayYellowCards    4070 non-null   int64
 15  HomeRedCards       4070 non-null   int64
 16  AwayRedCards       4070 non-null   int64
 17  PlayerName         4070 non-null   object
 18  PlayerTeam         4070 non-null   object
 19  PlayerPosition     4070 non-null   object
 20  PlayerNationality  3968 non-null   object
 21  PlayerAge          3932 non-null   float64
 22  PlayerCaps         3939 non-null   float64
 23  PlayerTries        4070 non-null   int64
 24  PlayerConversions  4070 non-null   int64
 25  PlayerPenalties    4070 non-null   int64
 26  PlayerYellowCards  4070 non-null   int64
 27  PlayerRedCards     4070 non-null   int64
 28  TacklesMade        3870 non-null   float64
 29  TacklesMissed      3864 non-null   float64
 30  MetresCarried      3874 non-null   float64
 31  Result             4070 non-null   object
dtypes: float64(5), int64(17), object(10)
memory usage: 1017.6+ KB

In [45]:
df.describe()

,MatchID,Round,HomeScore,AwayScore,HomeTriesScored,AwayTriesScored,HomePossession%,AwayPossession%,HomeYellowCards,AwayYellowCards,...,PlayerAge,PlayerCaps,PlayerTries,PlayerConversions,PlayerPenalties,PlayerYellowCards,PlayerRedCards,TacklesMade,TacklesMissed,MetresCarried
count,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,...,3932.000000,3939.000000,4070.000000,4070.000000,4070.000000,4070.000000,4070.000000,3870.000000,3864.000000,3874.000000
mean,2998.071253,4.526781,33.194349,32.958722,4.061671,3.983292,50.111302,49.888698,0.306634,0.293612,...,26.577823,59.916476,1.469779,0.183784,0.285995,0.079853,0.017936,10.079845,3.997930,90.303304
std,1154.711266,2.283893,16.681446,16.767101,2.575645,2.577807,8.861133,8.861133,0.564215,0.552955,...,3.940837,35.056515,1.118422,0.811948,0.873000,0.271098,0.132736,6.052248,2.583926,52.837338
min,1000.000000,1.000000,0.000000,0.000000,0.000000,0.000000,35.000000,35.000000,0.000000,0.000000,...,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1999.250000,3.000000,20.000000,19.000000,2.000000,2.000000,42.000000,42.000000,0.000000,0.000000,...,24.000000,29.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2.000000,44.000000
50%,3000.500000,5.000000,33.000000,32.000000,4.000000,4.000000,50.000000,50.000000,0.000000,0.000000,...,27.000000,60.000000,1.000000,0.000000,0.000000,0.000000,0.000000,10.000000,4.000000,92.000000
75%,3994.750000,6.750000,46.000000,46.000000,6.000000,6.000000,58.000000,58.000000,1.000000,0.000000,...,29.000000,90.000000,2.000000,0.000000,0.000000,0.000000,0.000000,15.000000,6.000000,136.000000
max,4999.000000,8.000000,74.000000,74.000000,8.000000,8.000000,65.000000,65.000000,2.000000,2.000000,...,40.000000,120.000000,3.000000,5.000000,4.000000,1.000000,1.000000,20.000000,8.000000,180.000000

In [46]:
df.isnull().sum()

MatchID                0
Date                   0
HomeTeam               0
AwayTeam               0
Venue                 88
Tournament            91
Round                  0
HomeScore              0
AwayScore              0
HomeTriesScored        0
AwayTriesScored        0
HomePossession%        0
AwayPossession%        0
HomeYellowCards        0
AwayYellowCards        0
HomeRedCards           0
AwayRedCards           0
PlayerName             0
PlayerTeam             0
PlayerPosition         0
PlayerNationality    102
PlayerAge            138
PlayerCaps           131
PlayerTries            0
PlayerConversions      0
PlayerPenalties        0
PlayerYellowCards      0
PlayerRedCards         0
TacklesMade          200
TacklesMissed        206
MetresCarried        196
Result                 0
dtype: int64

In [47]:
df.fillna(0)

,MatchID,Date,HomeTeam,AwayTeam,Venue,Tournament,Round,HomeScore,AwayScore,HomeTriesScored,...,PlayerCaps,PlayerTries,PlayerConversions,PlayerPenalties,PlayerYellowCards,PlayerRedCards,TacklesMade,TacklesMissed,MetresCarried,Result
0,1000,2019-04-08,France XV,New Zealand All Blacks,"Twickenham, London",World Rugby U20 Championship,2,52,5,8,...,104.0,0,0,0,0,0,13.0,5.0,71.0,Home Win
1,1001,2016-07-03,Georgia Rugby,Romania Rugby,"Estadio Jose Amalfitani, Buenos Aires",The Rugby Championship,6,33,11,3,...,86.0,2,0,0,0,0,2.0,2.0,136.0,Home Win
2,1002,2015-06-13,South Africa Springboks,Argentina Pumas,"Aviva Stadium, Dublin",Rugby World Cup,4,44,36,5,...,66.0,3,0,0,0,0,3.0,2.0,160.0,Home Win
3,1003,2023-05-25,New Zealand All Blacks,Ireland Rugby,"ANZ National Stadium, Suva",The Rugby Championship,2,22,51,4,...,0.0,2,0,0,0,0,16.0,0.0,153.0,Away Win
4,1004,2022-02-25,England Rugby,France XV,"Estadio Jose Amalfitani, Buenos Aires",Rugby Europe Championship,3,20,51,2,...,0.0,2,0,0,0,0,3.0,3.0,0.0,Away Win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4065,4005,2016-09-14,Canada Rugby,Samoa Rugby,"Teufaiva Stadium, Tonga",Autumn Internationals,7,34,48,6,...,59.0,3,0,0,0,0,7.0,2.0,176.0,Away Win
4066,3860,2024-02-06,Canada Rugby,Tonga Rugby,"National Stadium, Tokyo",Rugby World Cup,7,30,56,5,...,63.0,0,0,0,1,0,9.0,8.0,43.0,Away Win
4067,3854,2018-03-05,Canada Rugby,USA Eagles,"ANZ National Stadium, Suva",Pacific Nations Cup,4,50,23,7,...,51.0,1,0,0,0,0,12.0,7.0,92.0,Home Win
4068,2571,2021-05-01,Australia Wallabies,Italy Rugby,"Teufaiva Stadium, Tonga",Rugby Europe Championship,4,6,47,0,...,8.0,0,0,0,0,0,0.0,0.0,83.0,Away Win
4069,4806,2021-05-26,Argentina Pumas,Spain Rugby,"Stadium Australia, Sydney",The Rugby Championship,4,43,27,7,...,93.0,2,0,2,0,0,7.0,4.0,46.0,Home Win

In [48]:
df.duplicated().sum()

np.int64(70)

In [49]:
df.drop_duplicates()

,MatchID,Date,HomeTeam,AwayTeam,Venue,Tournament,Round,HomeScore,AwayScore,HomeTriesScored,...,PlayerCaps,PlayerTries,PlayerConversions,PlayerPenalties,PlayerYellowCards,PlayerRedCards,TacklesMade,TacklesMissed,MetresCarried,Result
0,1000,2019-04-08,France XV,New Zealand All Blacks,"Twickenham, London",World Rugby U20 Championship,2,52,5,8,...,104.0,0,0,0,0,0,13.0,5.0,71.0,Home Win
1,1001,2016-07-03,Georgia Rugby,Romania Rugby,"Estadio Jose Amalfitani, Buenos Aires",The Rugby Championship,6,33,11,3,...,86.0,2,0,0,0,0,2.0,2.0,136.0,Home Win
2,1002,2015-06-13,South Africa Springboks,Argentina Pumas,"Aviva Stadium, Dublin",Rugby World Cup,4,44,36,5,...,66.0,3,0,0,0,0,3.0,2.0,160.0,Home Win
3,1003,2023-05-25,New Zealand All Blacks,Ireland Rugby,"ANZ National Stadium, Suva",The Rugby Championship,2,22,51,4,...,NaN,2,0,0,0,0,16.0,0.0,153.0,Away Win
4,1004,2022-02-25,England Rugby,France XV,"Estadio Jose Amalfitani, Buenos Aires",Rugby Europe Championship,3,20,51,2,...,NaN,2,0,0,0,0,3.0,3.0,NaN,Away Win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,4995,2018-01-23,Wales Rugby,England Rugby,"Principality Stadium, Cardiff",Rugby World Cup,1,59,44,7,...,42.0,1,0,0,0,0,16.0,7.0,90.0,Home Win
3996,4996,2024-06-24,USA Eagles,Georgia Rugby,"Stadium Australia, Sydney",Six Nations,3,57,46,8,...,1.0,2,3,2,0,0,14.0,2.0,122.0,Home Win
3997,4997,2016-08-14,Scotland Rugby,Australia Wallabies,"Teufaiva Stadium, Tonga",The Rugby Championship,8,24,21,2,...,48.0,3,0,0,0,0,13.0,5.0,79.0,Home Win
3998,4998,2019-06-05,South Africa Springboks,Fiji Rugby,"Stadium Australia, Sydney",Autumn Internationals,7,43,49,4,...,22.0,3,0,0,0,0,8.0,7.0,122.0,Away Win
3999,4999,2022-09-01,France XV,Tonga Rugby,"National Stadium, Tokyo",The Rugby Championship,1,32,48,2,...,NaN,3,0,0,0,0,19.0,8.0,128.0,Away Win